### ISSUE TITLE
Shouldn't contact package archives all the time

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#11]
Each time I want to run linting or testing, emake contacts the package archives. This slows down my development process quite a lot as well as pollute the *compilation* buffer where I run `make`.

Would it be possible to install test dependencies through a dedicated make rule and then hope they are installed for the `test` make rule (or check and fail if dependencies are not installed).

**Comment by DamienCassou** [comment]
This would also let me only install dependencies when in CI. When on my development machine, I already have all dependencies in sibling directories so contacting package archives is useless.

**Comment by vermiculus** [comment]
Your suggestion makes sense, but I'm afraid that's just not how things were designed. emake.el is meant to be run from a CI and there, the packages need to be installed. I've thought about adding some kind of file 'flag' to indicate that the packages have been refreshed already (or to determine such from other state) and that would cut down on the number of requests, but I've no immediate on emake becoming an interactive tool.

**Comment by vermiculus** [comment]
To expand a bit further, the complication arises from how `emake-with-elpa` alters `package.el` state -- it will *always* use project subdirectory for pulling down dependencies. Those dependencies must not only be installed to run tests -- but they must also be in `load-path`. This is something handled by `package-initialize` if and only if things are set up as it expects.

Leaving this issue open to track the 'don't need to refresh ELPAs all the time' deal. We'll need to take care that every archive is initialized exactly once.

**Comment by DamienCassou** [comment]
> I've no immediate on emake becoming an interactive tool

I also don't want to use emake interactively. But I want to be able to execute my make rules from my development machine. For example, `make test` should work both on a CI server and locally.

**Comment by vermiculus** [comment]
This is already possible though; at least as far as I can reproduce. Can you give more explicit details on your setup?

**Comment by vermiculus** [comment]
I've done the easy part – now for the hard part of figuring out what use case I'm missing XD

**Comment by DamienCassou** [comment]
I'm quite happy with the setup right now. I pushed a PR for libmpdel at https://gitlab.petton.fr/mpdel/libmpdel/merge_requests/22. I think we can close this ticket.
