### ISSUE TITLE
Make elmake silent

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#12]
emake is writting a lot to stdout which is making what I care about (test results) lost in the noise. I suggest:

1. giving a priority level to messages (e.g., error, warning, info)
2. adding a variable to choose which priority level should be displayed

A simpler approach could be:

1. removing all unnecessary messages (e.g., "initializing package.el")
2. adding a variable to hide even the other messages (e.g., `emake-silent` or `emake-verbose`)

**Comment by DamienCassou** [comment]
Yet another approach would be to merge many messages into one. For example,

```
emake: compiling libmpdel.el...
emake: compiling libmpdel.el...done
emake: compiling test/libmpdel-test.el...
emake: compiling test/libmpdel-test.el...done
```

could be simplified to:

```
emake: compiling libmpdel.el test/libmpdel-test.el
```

**Comment by vermiculus** [comment]
Why not just grep out `^emake:.*`?

**Comment by DamienCassou** [comment]
Sean Allred <notifications@github.com> writes:
> Why not just grep out `^emake:.*`?

that's a valid workaround :-).

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
