### ISSUE TITLE
Refining what to check

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#13]
EMake considers the files in `PACKAGE_LISP` for (1) compilation, (2) checkdoc and (3) package-lint. Typically, every non-test file in my projects can be checked against (1), (2) and (3). Test files on the other hand, only respect (1) and (2) but not (3). My test files are not respecting (3) mostly because the typical namespace of a test file is the filename without `-test.el`. This is enforced by [nameless](https://github.com/Malabarba/Nameless/blob/master/nameless.el#L288).

Because a test file doesn't respect (3), I can't run (1) and (2) on them and I find that annoying.

**Comment by vermiculus** [comment]
`PACKAGE_LISP` is documented thus:

> This contains a space-delimited list of files to be considered part of the package.

It was not originally intended to include your test suite – only the actual distribution.

Since you can alter `PACKAGE_LISP` on a target-by-target basis in a Makefile, I'm not inclined to change this definition.
