### ISSUE TITLE
emake complains packages aren't installable during "make test"

### ISSUE THREAD

**Issue by stsquad** [vermiculus/emake.el#15]
To avoid polluting the commit thread I have created this issue. I see this when running locally for my repo stsquad/dired-rsync:

    Importing package-keyring.gpg...
    Importing package-keyring.gpg...done
    Contacting host: stable.melpa.org:80
    Contacting host: stable.melpa.org:80
    Package refresh done
    emake: [.elpa.test/] downloading archives: (("melpa-stable" . "http://stable.melpa.org/packages/"))...done
    emake: installing s...
    Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
    Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
    Making version-control local to s-autoloads.el while let-bound!
    Generating autoloads for s.el...
    Generating autoloads for s.el...done

    Checking /home/alex/mysrc/dired-rsync.git/.elpa.test/s-1.12.0...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/s-1.12.0/s-autoloads.el...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/s-1.12.0/s-pkg.el...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/s-1.12.0/s.el...
    Done (Total of 1 file compiled, 2 skipped)
    emake: installing s...done
    emake: installing dash...
    Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
    Contacting host: stable.melpa.org:80
    Generating autoloads for dash.el...
    Generating autoloads for dash.el...done

    Checking /home/alex/mysrc/dired-rsync.git/.elpa.test/dash-2.14.1...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/dash-2.14.1/dash-autoloads.el...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/dash-2.14.1/dash-pkg.el...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/dash-2.14.1/dash.el...
    Done (Total of 1 file compiled, 2 skipped)
    emake: installing dash...done
    emake: installing package-lint...
    Setting ‘package-selected-packages’ temporarily since "emacs -q" would overwrite customizations
    Generating autoloads for package-lint.el...
    Generating autoloads for package-lint.el...done

    Checking /home/alex/mysrc/dired-rsync.git/.elpa.test/package-lint-0.5...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/package-lint-0.5/package-lint-autoloads.el...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/package-lint-0.5/package-lint-pkg.el...
    Compiling /home/alex/mysrc/dired-rsync.git/.elpa.test/package-lint-0.5/package-lint.el...
    Done (Total of 1 file compiled, 2 skipped)
    emake: installing package-lint...done
    emake: installing test suite dependencies into .elpa.test...done
    emake: Detected test-runner as ‘package-lint-batch-and-exit’
    emake: running test...
    In ‘dired-rsync.el’:
      at 8:24: error: Package s is not installable.
    make: *** [Makefile:57: test-package-lint] Error 1

It is also doesn't work up on Travis, see https://travis-ci.org/stsquad/dired-rsync/jobs/385651589 and I note the vermiculus/emake.el-example@cb4f80a2d3d513cdcf6f2de6e90876eb055b9d16 is also currently broken.

**Comment by vermiculus** [comment]
I'll figure out what's going on tonight.

**Comment by vermiculus** [comment]
Looks like [this is coming from `package-lint`](https://github.com/purcell/package-lint/blob/69bb89d00ba212b734c676ad056aa793c450b288/package-lint.el#L469), actually.

**Comment by vermiculus** [comment]
`package-archives` isn't being set correctly.

**Comment by vermiculus** [comment]
Looks like this regression was introduced in 33957b8823b949d2f71aba8e342c1e658994f701.

**Comment by vermiculus** [comment]
`package-lint` requires variable `package-archives` to be set up correctly; see [its example](https://github.com/purcell/package-lint/blob/69bb89d00ba212b734c676ad056aa793c450b288/run-tests.sh#L7). We used to include `(funcall test-runner)` in `emake-with-elpa` which sets up `package-archives`, but this was moved out for an unknown reason.
