### ISSUE TITLE
Add which files are being linted

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#19]
There are many messages in the log, but none of them say which files are being checked with checkdoc and package-lint. Would it be possible to display this information?

**Comment by vermiculus** [comment]
For package-lint, you should ask for this [upstream](https://github.com/purcell/package-lint). I'll add the handling for checkdoc 👍

**Comment by DamienCassou** [comment]
Instead of displaying one line for each file and each check, would it be possible to have one line listing all the files being checked together? I opened PR https://github.com/vermiculus/emake.el/pull/21 with a possible implementation.
