### ISSUE TITLE
Extract sample to different repository

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#2]
To simplify understanding of both the package implementation and how to use it, I suggest moving the sample file to their own repository, e.g., emake-sample.

**Comment by vermiculus** [comment]
That may be a good idea -- just to keep things clean. I fought with Travis for a bit concerning the location of `.travis.yml`, so doing this would clear that up. I'd still like to include it as a submodule in this repository, though.

**Comment by vermiculus** [comment]
Thanks for the idea!
