### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#22]
Would you mind releasing an initial version of emake? It doesn't have to be 1.0.0 if you don't feel ready. Please use https://semver.org/ if possible. I think using a version number would be clearer than a SHA in `EMAKE_SHA1`.

**Comment by vermiculus** [comment]
Why?

**Comment by vermiculus** [comment]
To expand, I'm not keen on making tagged releases for EMake because it implies only those versions that have been released are stable. All commits to `master` should be 'stable', so you should be able to just grab the most recent SHA1 and run with that. At the end of the day, if it gets your testing done correctly, why impose an additional system on top?

**Comment by DamienCassou** [comment]
Version numbers (especially through semantic versioning) allow meaning to be conveyed: the new version is a bug fix, contains new features, or break backward compatibility. This makes it easier for your users to decide when to upgrade.

When I change EMake's SHA1 in my Makefile, it's not even clear if I'm upgrading emake or downgrading it.

That being said, maintaining version numbers is indeed a bit of additional work that you might not be willing to do. Feel free to close the issue.

**Comment by vermiculus** [comment]
I just don't see the value in it. If a particular version works for someone, why would they care to upgrade? The only reason they'd want to would be to get new features which they would have to learn from the readme. I'm not against tagged versions completely, but I don't see the value for a tool like this. 

When I'm deciding to upgrade something, I'm doing so from list-packages or similar. It's a tool I'm going to be using interactively. EMake is not an interactive tool in this sense, so is there still value in upgrading?
