### ISSUE TITLE
Check compilation of test files

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#23]
In https://github.com/DamienCassou/beginend, I would like to test that files in `test/` compile without warning. Usually, I do things like that this way:

```Makefile
lint: PACKAGE_LISP += $(filter-out test/test-helper.el, ${PACKAGE_TESTS})
lint: lint-checkdoc lint-package-lint compile
```

The problem here is that the files in `test/` depend on `assess` and `buttercup` which Emacs can't find at the time it starts the byte compiler.

I can't find any workaround without touching emake.el or emake.mk.

**Comment by vermiculus** [comment]
I don't see why you would *want* to compile a test file.

You can always write your own targets :-)

**Comment by DamienCassou** [comment]
> I don't see why you would want to compile a test file.

I want to make sure that my code is of top quality. Test code included. Checking that my test code compiles without waning is important to me.

> You can always write your own targets :-)

Then I would need a separate elisp file that I would have to save in a separate repository and fix the build process of all my elisp projects so they can benefit from it. This defeats the purpose of emake in my opinion.

**Comment by vermiculus** [comment]
It is not emake's purpose to be a catch-all dumping ground for all the different kinds of tests one could remotely want to do. There are some test types (like [ghub+'s reading linter](https://github.com/vermiculus/ghub-plus/blob/master/test/linter.el)) that will never be in-scope for emake.

I wouldn't shoot down a pull request implementing a compile-tests target, but I'm not going to implement it myself, either. I would still need convincing that having tests compile without warning is a real indicator of code quality.

Closing this issue for now as I don't intend on implementing it myself, but we can of course continue discussion here.
