### ISSUE TITLE
Running package-lint on every file

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#24]
I make sure each and every Emacs lisp file of my projects are compliant with package-lint. With your commit ed39e5203877e0e811df29171922ff2a5dcd6368, I have the impression you would like that only one file is checked per project. I understand the rationale as package-lint is supposed to check the package metadata which should only be present in the root file. Nevertheless, package-lint has grown to check much more than that and I care about all those checks in all my files.

**Comment by vermiculus** [comment]
I would prefer *all* files be checked, but as the commit message and linked package-lint issue states, multi-file packages are not yet supported by package-lint. Unless you were able to get around tens of issues per file about missing package headers (and do let me know if you have!), this change is staying until upstream can be updated to avoid this.

If you would like to keep the old behavior, you can export PACKAGE_FILE := $(PACKAGE_LISP) in your linting target.

**Comment by DamienCassou** [comment]
Sean Allred <notifications@github.com> writes:
> Unless you were able to get around tens of issues per file about
> missing package headers (and do let me know if you have!),

I just add package headers to every file:

https://gitlab.petton.fr/mpdel/mpdel


It's no big deal and it makes package-lint check every line of code.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by vermiculus** [comment]
I don't think I want to encourage that kind of duplication -- especially things like package.el-sensitive headers like `Package-Requires` and `Version`.

Good conversation for purcell/package-lint#111.
