### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#3]
Many projects have at least one dependency beyond Emacs itself. I suggest adding a way to specify dependencies. I have been [doing that](https://github.com/mpdel/libmpdel/blob/master/Makefile#L18) [with Makefiles](https://github.com/mpdel/ivy-mpdel/blob/master/Makefile#L21) for some time [and others have too](https://github.com/magit/magit/blob/master/default.mk#L117).

**Comment by vermiculus** [comment]
Dependencies are calculated from the standard `Package-Requires` header. Does this not work?

https://github.com/vermiculus/emake.el/blob/75793730ae7dbc870039513cce7b3f679443ba7f/emake.el#L166-L180

**Comment by vermiculus** [comment]
Let me know if this isn't working for you – in about a week, I'll probably clean up stale issues on my projects. This will then be closed since (as far as I can tell) package dependencies are being parsed installed as designed.

**Comment by DamienCassou** [comment]
Thank you for answering @vermiculus. Your approach makes things already much simpler than handling dependencies manually. Nevertheless, I see a limitation that would prevent me from using EMake: non-elpa dependencies. I have at least two use-cases:

1. on my development machine, I don't use elpa at all but `git submodules` with [borg](https://github.com/emacscollective/borg). This makes it a breeze to contribute to any project I use. In this use-case, I don't want EMake to download any dependency I already have installed. This is why I add "../libmpdel" to `LOAD_PATH` in [mpdel](https://gitlab.petton.fr/mpdel/mpdel/blob/master/Makefile#L4). This is also the approach used by [Magit's makefile](https://github.com/magit/magit/blob/master/default.mk#L11).

2. on my CI slaves (either Travis or GitLab CI), building a project sometimes require a more recent dependency than what is currently on melpa. This happens frequently for projects decomposed into several packages. For example, my MPD client is decomposed into [libmpdel](https://gitlab.petton.fr/mpdel/libmpdel), [mpdel](https://gitlab.petton.fr/mpdel/mpdel) and [ivy-mpdel](https://gitlab.petton.fr/mpdel/ivy-mpdel). I regularly update libmpdel and then want to test mpdel using the latest commit of libmpdel before melpa has built it (several hours will pass between I make a commit and Melpa builds it). This is why [I use `curl` for that](https://gitlab.petton.fr/mpdel/mpdel/blob/master/Makefile#L28).

An easy solution for EMake would be to let the developer specify a list of externally-managed dependencies. EMake would then have to be changed in 2 ways:

1. Before installing any dependency, EMake should check if the dependency is in the list of externally-managed dependencies and if it is, avoid installing it
2. Before loading the package, EMake should add to `load-path` the elements provided by the user.

For mpdel, this could look like:

```Makefile
EENVS += PACKAGE_EXTERNAL_DEPENDENCIES="libmpdel"
EENVS += PACKAGE_LOAD_PATH="../libmpdel"
```

**Comment by vermiculus** [comment]
I can see the case for adding a variable `PACKAGE_IGNORE_DEPS` that will instruct EMake to avoid installing those actual package dependencies and rely on the caller to handle installing and loading those, however I don't see a big enough benefit to your `PACKAGE_LOAD_PATH`. Here's how I'd handle that case (untested):

``` makefile
EENVS := [...]
EENVS += PACKAGE_IGNORE_DEPS="libmpdel"
ELOAD := ../libmpdel
EEVAL := (progn $(foreach dir,$(ELOAD),(add-to-list \'load-path "$(dir)")))

EMAKE := $(EENVS) emacs -batch -l emake.el --eval "$(EEVAL)" --eval "(emake (pop argv))"
```

What are your thoughts?

**Comment by DamienCassou** [comment]
> What are your thoughts?

you can probably just pass `-L` options to `emacs`:

```Makefile
EENVS := [...]
EENVS += PACKAGE_IGNORE_DEPS="libmpdel"
ELOAD := -L ../libmpdel

EMAKE := $(EENVS) emacs -batch $(ELOAD) -l emake.el --eval "$(EEVAL)" --eval "(emake (pop argv))"
```

**Comment by vermiculus** [comment]
Genius. So, would just a `PACKAGE_IGNORE_DEPS` variable be the best thing here? Looks like the previous `PACKAGE_LOAD_PATH` would be a duplication of `-L`.

**Comment by DamienCassou** [comment]
Sean Allred <notifications@github.com> writes:
> So, would just a `PACKAGE_IGNORE_DEPS` variable be the best thing
> here?

let's try :-).

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
