### ISSUE TITLE
emake powered CI stopped working, unable to fix

### ISSUE THREAD

**Issue by stsquad** [vermiculus/emake.el#31]
I got a PR after about 6 months of quietness and discovered the CI was broken (see https://travis-ci.org/stsquad/dired-rsync/builds). I noticed there had been a bunch of changes so I updated my emake setup as per the latest example. However things were still broken. On closer examination:

  https://travis-ci.org/stsquad/dired-rsync/jobs/499491487
vs
  https://travis-ci.org/vermiculus/emake.el-example/jobs/497975087

I realised that the latest sample builds were relying on their cached emacs builds (Emacs found at /home/travis/emacs/src/emacs; abort). So I downgraded the emake version but it still weirdly fails:

  https://travis-ci.org/stsquad/dired-rsync/jobs/499498430

Which is odd and kinda implies the underlying Travis environment has changed in a subtle way that breaks the emacs build machinery. Any idea where things have gone of the rails?

**Comment by vermiculus** [comment]
I would try kicking of a build where the first thing you do is sudo rm -rf your cached directory. Will your build work if you do that?

I'm mobile right now but I can take a peek at your setup later if that doesn't work.

**Comment by vermiculus** [comment]
Looks like this did indeed fix the issue for you, so you should be able to fix those package-lint errors and push a new build (and remove the `sudo rm -rf $HOME/emacs` bit -- the cache should be clean now).

**Comment by vermiculus** [comment]
...once the build completely finishes, of course -- that should probably include your snapshot builds, just to be on the safe side. Usually takes about 15-20 minutes depending on how many people want OS X VMs.

I want to re-work the documentation to make things simpler to find -- I'll leave this issue open for that since I should probably mention how to resolve this kind of issue (I ran into a couple times myself).

**Comment by stsquad** [comment]
Yes that seems to have unwedged it. Perhaps the install script can do a sanity check. By the way you should be able to drop the cache from the GUI rather than hack your .travis.yml

**Comment by vermiculus** [comment]
Ooo, I didn't even know to look for such a thing, thanks!

As for the sanity check, perhaps it could touch a file like `emake-v1`?
