### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by DamienCassou** [vermiculus/emake.el#5]
My projects use several kinds of linting that I would prefer delegating to EMake rather than copy/pasting everywhere:

1. Byte compile all and stop on any warning or error: [example](https://gitlab.petton.fr/mpdel/libmpdel/blob/v0.5.0/Makefile#L31)
2. Run [package-lint](https://github.com/purcell/package-lint) to check for packaging mistakes: [example](https://gitlab.petton.fr/mpdel/libmpdel/blob/v0.5.0/Makefile#L36)
3. Run checkdoc to check Emacs Lisp conventions: [example](https://gitlab.petton.fr/mpdel/libmpdel/blob/a474f4d3e867b3ffedf88915f73d9109349b2655/Makefile#L42)
4. Load all source files in the same Emacs to find conflicts: [example](https://gitlab.petton.fr/mpdel/mpdel/blob/v0.4.0/Makefile#L37)

**Comment by vermiculus** [comment]
ef2369087aa44b8f0877f13b83bdef46260b8458 added the ability to error on warnings, so you can already do this by also specifying `PACKAGE_LISP` which notes all the files to be considered part of the source.

2–4 sound like good enhancements in their own right and should ideally be tracked independently. (2) and (3) can probably just be another test backend in `emake-test-runner-master-alist`, so I'll probably just add those now. So we'll just turn this issue into (4).

What do you mean by 'conflict'? Like multiple definitions for the same symbol?

**Comment by vermiculus** [comment]
Also, I'm not able to get `checkdoc-file` to actually fail when there are style issues. Does your makefile actually do that successfully?

**Comment by vermiculus** [comment]
Hacked around that issue, so only (4) is left :-)

**Comment by DamienCassou** [comment]
> What do you mean by 'conflict'? Like multiple definitions for the same symbol?

The only use case I found for (4) was when a file was declaring a `defun` and another file was declaring a `cl-defgeneric` of the same name. I don't care that much about this as I think it's quite rare. Nice to have though.

**Comment by DamienCassou** [comment]
> Also, I'm not able to get checkdoc-file to actually fail when there are style issues. Does your makefile actually do that successfully?

yes. The following detects if a function's docstring does not reference an argument:

```
emacs -Q --batch --eval "(mapcar #'checkdoc-file '( \"libmpdel.el\"))"
```

**Comment by vermiculus** [comment]
Does that exit with a non-zero status, though?

**Comment by DamienCassou** [comment]
you are right, it does *not* :-(.

**Comment by vermiculus** [comment]
I did find a way to hack around it even if my approach is a bit fragile. Hopefully you can find some use from it :-)

Looks like 1–3 should be addressed. Let me know your thoughts on (4) :)

**Comment by DamienCassou** [comment]
I think we should close the issue now. I will open more focused issues/PRs if needed.
